# Winlogbeat örnek konfigürasyonu
# Bu örnek, WEF/WEC üzerinde ForwardedEvents kanalını okuyup Logstash'e gönderir.
# Elastic Stack sürümünüzle uyumlu Winlogbeat sürümünü kullanın (ör. 8.11.x).
winlogbeat.event_logs:
  - name: ForwardedEvents
    ignore_older: 72h

# Eğer Logstash üzerinden gönderiyorsanız output.logstash bölümünü kullanın
output.logstash:
  hosts: ["<SIEM_HOST_IP>:5044"]

# TLS kullanıyorsanız aşağıdaki örneği etkinleştirin ve Logstash sertifika CA'sını verin
#output.logstash:
#  hosts: ["<SIEM_HOST_IP>:5044"]
#  ssl.enabled: true
#  ssl.certificate_authorities: ["/path/to/http_ca.crt"]

# Lokal debugging için console output (opsiyonel)
#logging.level: info
#logging.to_files: true
#logging.files:
#  path: C:/ProgramData/winlogbeat/logs
#  name: winlogbeat
#  keepfiles: 7
#  permissions: "0644"
