#cloud-config
# Example cloud-init for provisioning a VM and running the installer non-interactively.
# Replace REPLACE_ME with a strong password before using, or inject via your cloud provider's secrets.

package_update: true
packages:
  - git

runcmd:
  # clone repo (or update if already present)
  - [ bash, -lc, 'if [ -d /root/elk ]; then cd /root/elk && git pull || true; else git clone https://github.com/yusufarbc/ELK-Ubuntu-Jammy-Build.git /root/elk; fi' ]
  # ensure installer is executable
  - [ bash, -lc, 'chmod +x /root/elk/elk_setup_ubuntu_jammy.sh' ]
  # run installer non-interactive (replace REPLACE_ME with a real password or inject via provider)
  - [ bash, -lc, 'ELASTIC_PW="REPLACE_ME" /root/elk/elk_setup_ubuntu_jammy.sh --non-interactive --password "$ELASTIC_PW"' ]

# optional: write a small marker file on success
final_message: "The system is finally up, and the installer was invoked. Check /root/elk for logs."
