# NOTE: The test harness previously included a Docker Compose file for running a Logstash container.
# The repository now provides a Docker-less Python-based harness (`run_test_harness.py`) to validate
# Logstash filter logic locally. Prefer the Python harness for quick, dependency-light testing.
