# Minimal Logstash config used in Docker Compose mount
http.host: "0.0.0.0"
queue.type: persisted
path.data: /usr/share/logstash/data
path.logs: /usr/share/logstash/logs
config.reload.automatic: false
