name: Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    name: Shellcheck
    steps:
      - uses: actions/checkout@v4
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@v1
        with:
          files: |
            elk_setup_ubuntu_jammy.sh

  markdownlint:
    runs-on: ubuntu-latest
    name: MarkdownLint
    steps:
      - uses: actions/checkout@v4
      - name: Lint Markdown
        uses: wavded/markdownlint-action@v1
        with:
          files: |
            README.md
            CONFIGURATIONS.md
            SINGLE_HOST_QUICKSTART.md
