name: Logstash Test Harness

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-harness:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Run test harness
        run: |
          python3 tools/logstash_test/run_test_harness.py
          pytest -q tools/logstash_test/test_harness.py
